# fly.toml file generated for my-app-countries on 2022-10-11T20:31:43-03:00

app = "my-app-countries"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DDL_AUTO = "update"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED = "false"
  SPRING_PROFILES_ACTIVE="prod,api-docs"
  SPRING_DATASOURCE_PASSWORD = "j2rXgUCjb5B9AzeIziXEngZj8fiOh1ka"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://dpg-cd610lmn6mprs1p6qvk0-a:5432/countries_docker_db"
  SPRING_DATASOURCE_USERNAME = "countries_docker_db_user"
  SPRING_LIQUIBASE_URL = "jdbc:postgresql://dpg-cd610lmn6mprs1p6qvk0-a:5432/countries_docker_db"
  SPRING_OPEN_IN_VIEW = "false"
  _JAVA_OPTIONS = "-XX:MaxRAM=256m"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
