# fly.toml file generated for my-app-countries on 2022-10-11T20:31:43-03:00

app = "my-app-countries"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DDL_AUTO = "update"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED = "false"
  SPRING_DATASOURCE_PASSWORD = "f60dfdbd360f49e50b274063112cd07bcbfa7451247287eb"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://app-docker-db.internal:5432/app_docker?options"
  SPRING_DATASOURCE_USERNAME = "postgres"
  SPRING_LIQUIBASE_URL = "jdbc:postgresql://app-docker-db.internal:5432/app_docker?options"
  SPRING_OPEN_IN_VIEW = "false"
  _JAVA_OPTIONS = "-XX:MaxRAM=256m"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
