# Spring configurations
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: false
  security:
    require-ssl: false
  # Database
  datasource:
    url: jdbc:postgres://postgres:16e9820c80b4da1a887ca3e1cc9e4083174ce4e0457f27f3@app-docker-db.internal:5432/app-docker-db?options
    username: postgres
    password: 16e9820c80b4da1a887ca3e1cc9e4083174ce4e0457f27f3

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Server configuration
  server:
    port: 8080
    ssl:
      enabled: false
