# Spring configurations
spring:
  main:
    allow-bean-definition-overriding: false
  security:
    require-ssl: false
  # Database
  datasource:
    url: jdbc:postgresql://dpg-cd610lmn6mprs1p6qvk0-a:5432/countries_docker_db
    username: countries_docker_db_user
    password: j2rXgUCjb5B9AzeIziXEngZj8fiOh1ka

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Server configuration
  server:
    port: 8080
    ssl:
      enabled: false
